apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: rhacm-thanos-bucket-a89a03d3-4956-4c23-a466-49092657874c
      endpoint: s3-openshift-storage.apps.ocp4.stormshift.coe.muc.redhat.com:80
      insecure: true
      access_key: gvJ7knEAxQrcLknvCaOR
      secret_key: gUbbrs+N66vXEgrvxm2WBBjgFKtHVl83nsaVmho4
