---
- name: Create Virtual Network
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - cfg/secrets.yml
    - cfg/stormshift.yml

  vars:
    engine_user: admin@internal
    engine_password: "{{secret_password}}"
    engine_url: https://{{layer2_rhev_engine_fqdn}}/ovirt-engine/api
    wait_for_ip: true
    debug_vm_create: true

  tasks:
    - name: Login into RHEV
      tags: always
      ovirt_auth:
       url: "{{layer2_rhev_engine_url}}"
       username: "{{layer2_rhev_engine_user}}"
       password: "{{layer2_rhev_engine_password}}"

    - name: Create virtual network
      tags: net,broken
      ovirt_network:
        auth: "{{ ovirt_auth }}"
        state: present
        data_center: Default
        name: "{{layer3_ocp_name}}-network"
        vm_network: true
        mtu: 1442
        external_provider: ovirt-provider-ovn

- name: Configure Layer1 DNS
  hosts: layer1
  gather_facts: false
  vars_files:
    - cfg/secrets.yml
    - cfg/stormshift.yml

  tasks:
    - name: Add DNS entries
      tags: dns
      blockinfile:
        path: /etc/named/{{ sysctx_dns_domain }}.zone
        marker: "; {mark} ANSIBLE MANAGED BLOCK {{layer3_ocp_name}}"
        block: |
          {{layer3_ocp_name}}bastion IN A {{layer3_ocp_bastion_ip}}
          {{layer3_ocp_name}}support IN A 172.16.10.5
          *.apps.{{layer3_ocp_name}}.{{sysctx_dns_domain}}.	IN A {{layer3_ocp_bastion_ip}}
          api.{{layer3_ocp_name}}.{{sysctx_dns_domain}}.	IN A {{layer3_ocp_bastion_ip}}
          ; Forward to cluster specifc DNS Server which is running on support behind bastion
          ;$ORIGIN {{layer3_ocp_name}}.stormshift.coe.muc.redhat.com.
          ;@       IN      NS      {{layer3_ocp_bastion_ip}}
      register: dns

    - name: Restart DNS
      tags: dns
      service:
        name: named
        enabled: yes
        state: restarted
      when: dns is changed



- name: Create Virtual Machines
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - cfg/secrets.yml
    - cfg/stormshift.yml

  vars:
    engine_user: admin@internal
    engine_password: "{{secret_password}}"
    engine_url: https://{{layer2_rhev_engine_fqdn}}/ovirt-engine/api
    wait_for_ip: true
    debug_vm_create: true

# this role actually creates the VMs:
# Checkout variable "vm" in cfg/ocp(1-5).yml, esp. "profiles" and "vms
# they define what the vm-infra role will create here:
  roles:
    - role: ovirt.vm-infra
      tags: vms,slow
      vars:
        wait_for_ip: false

- name: Configure Bastion
  hosts: "{{layer3_ocp_name}}bastion.stormshift.coe.muc.redhat.com"
  gather_facts: false
  vars_files:
    - cfg/secrets.yml
    - cfg/stormshift.yml
  tasks:
    - name: Remove cloud init
      tags: bastion,slow
      yum:
        name: cloud-init
        state: absent

    - name: Install packages
      tags: bastion,slow
      yum:
        name:
          - bind-utils
          - haproxy
          - firewalld
          - tftp
        state: latest

    - name: Install container tools
      tags: bastion,slow,podman,broken
      yum:
        name: "@container-tools"
        state: latest

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Enable IP Forwarding
      tags: bastion,firewall
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        reload: yes

    - name: Start firewall
      tags: bastion,firewall
      service: name=firewalld enabled=yes state=started

    - name: add ens2 to external zone
      tags: bastion,firewall
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled
        zone: external
        interface: ens2

    - name: add ens5 to internal zone
      tags: bastion,firewall
      firewalld: immediate=yes permanent=yes state=enabled zone=internal interface=ens5

    - name: add masquerade to external zone
      tags: bastion,firewall
      firewalld: immediate=yes permanent=yes state=enabled zone=external masquerade=yes

    - name: add passthrough to ens2
      tags: bastion,firewall
      shell: "firewall-cmd --permanent --direct --passthrough ipv4 -t nat -I POSTROUTING -o ens2 -j MASQUERADE -s {{layer3_ocp_network_prefix}}.0/24"
      register: fwresult
      changed_when: "fwresult.stderr is not search('ALREADY_ENABLED')"

    - name: Open internal service ports
      tags: bastion,firewall
      firewalld: immediate=yes permanent=yes state=enabled zone=internal service="{{ item}}"
      with_items:
        - tftp
        - dns
        - http
        - https
        - nfs
        - ssh

    - name: Open OpenShift API Port 6443 to internal
      tags: bastion,firewall
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled
        zone: internal
        port: 6443/tcp

    - name: Open Machine Config Port 22623 to internal
      tags: bastion,firewall
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled
        zone: internal
        port: 22623/tcp


    - name: Open external service ports
      tags: bastion,firewall
      firewalld: immediate=yes permanent=yes state=enabled zone=external service="{{ item}}"
      with_items:
        - http
        - https
        - ssh

    - name: Open OpenShift API Port 6443 to external
      tags: bastion,firewall
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled
        zone: external
        port: 6443/tcp

    - name: Workaround strange not persited problem
      tags: bastion,firewall
      shell: firewall-cmd --runtime-to-permanent
      changed_when: false

# Bastion Load balancer service via container provided by ssa stc:
    - name: Provide LB Container Service Config
      tags: bastion,lb
      template:
        src: templates/ocp4loadbalancer.service.j2
        dest: /etc/systemd/system/openshift-4-loadbalancer.service

    - name: Start Loadbalancer Service
      tags: bastion,lb
      service:
        name: openshift-4-loadbalancer
        enabled: yes
        state: started

#    - name: Add Domain to resolv.conf
#      tags: bastion,dns
#      template:
#        src: templates/ocp4resolv.conf.j2
#        dest: /etc/resolv.conf


# TODO: Deployment breaks here with "host unreachable" - understand why and FIX
    - name: Copy SSH Keys to bastion
      tags: bastion,misc
      copy:
        src: /home/hailstorm/.ssh/{{ item}}
        mode: preserve
        dest: /root/.ssh/
      with_items:
        - id_rsa
        - id_rsa.pub
        - config

# -------------------------------------------------
# -------------------------------------------------
# ---------------  SUPPORT SERVER -----------------
# -------------------------------------------------
# -------------------------------------------------

- name: Configure Support
  hosts: "{{layer3_ocp_name}}support.stormshift.coe.muc.redhat.com"
  gather_facts: false
  vars_files:
    - cfg/secrets.yml
    - cfg/stormshift.yml
  tasks:
    - name: Remove cloud init
      tags: support,slow
      yum:
        name: cloud-init
        state: absent

    - name: Install packages
      tags: support,slow
      yum:
        name:
          - bind
          - bind-utils
          - dhcp-server
          - httpd
          - nfs-utils
          - tftp-server
          - tftp
          - xinetd
          - tar
          - syslinux
          - jq
        state: latest

    - name: upgrade all packages
      tags: support,slow
      yum:
        name: '*'
        state: latest

# -------------------------------------------------
# ----------------------- setup bind as DNS Server
    - name: Configure BIND to listen on all ports
      lineinfile:
        regexp: ".*listen-on port 53.*"
        line: "  listen-on port 53 { 127.0.0.1; 172.16.10.5; };"
        path: /etc/named.conf
      tags: support,dns

    - name: Configure BIND not to listen on ipv6
      tags: support,dns
      lineinfile:
        line: 'OPTIONS="-4"'
        path: /etc/sysconfig/named

    - name: configure BIND to answer external queries
      tags: support,dns
      lineinfile:
        line: "  allow-query     { any; };"
        regexp: ".*allow-query.*"
        path: /etc/named.conf

    - name: configure BIND to forward to stormshift dns
      tags: support,dns
      lineinfile:
        line: "  forwarders { {{layer1_host_ip_adress}};};"
        regexp: ".*forwarders.*"
        insertafter: ".*allow-query.*"
        path: /etc/named.conf

    - name: create a sensible serial for BIND zone
      tags: support,dns
      shell: date +%Y%m%d$((`date +%-H`*4+`date +%-M`/8))
      register: bind_zone_serial
      changed_when: False

    - name: create zone file
      tags: support,dns
      template:
        src: templates/ocp4bind.zone.j2
        dest: /etc/named/{{layer3_ocp_name}}.{{ sysctx_dns_domain }}.zone

    - name: create reverse zone file
      tags: support,dns
      template:
        src: templates/ocp4bind.reverse.zone.j2
        dest: /etc/named/10.16.172.in-addr.arpa.zone

    - name: add zone db to bind config
      tags: support,dns
      lineinfile:
        line: "zone \"{{layer3_ocp_name}}.{{ sysctx_dns_domain }}\" { type master; file \"/etc/named/{{layer3_ocp_name}}.{{ sysctx_dns_domain }}.zone\"; };"
        path: /etc/named.rfc1912.zones

    - name: add reverse zone db to bind config
      tags: support,dns
      lineinfile:
        line: "zone \"10.16.172.in-addr.arpa\" { type master; file \"/etc/named/10.16.172.in-addr.arpa.zone\"; };"
        path: /etc/named.rfc1912.zones

    - name: Enable dns server
      tags: support,dns
      service:
        name: named
        enabled: yes
        state: restarted

    - name: Open Firewall for dns
      tags: support,dns
      firewalld:
       service: dns
       permanent: yes
       immediate: yes
       state: enabled

    - name: Add Domain to resolv.conf
      tags: support,dns
      template:
        src: templates/ocp4resolv.conf.j2
        dest: /etc/resolv.conf

# -------------------------------------------------
# ----------------------- setup DHCP Server

    - name: Provide dhcpd conf
      tags: support,dhcp
      template:
        src: templates/ocp4dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
      register: dhcp_conf

    - name: Enable and restart dhcp server
      tags: support,dhcp
      service:
        name: dhcpd
        enabled: yes
        state: restarted
      when: dhcp_conf is changed

    - name: Open Firewall for dhcp
      tags: support,dhcp
      firewalld:
       service: dhcp
       permanent: yes
       immediate: yes
       state: enabled

# -------------------------------------------------
# ----------------------- setup httpd Server
    - name: Enable and start http server
      tags: support,http
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Open Firewall for httpd
      tags: support,http
      firewalld:
       service: http
       permanent: yes
       immediate: yes
       state: enabled

# -------------------------------------------------
# ----------------------- setup nfs Server
    - name: Make directory for nfs export
      tags: support,nfs
      file:
        path: "/data/nfs/ocp"
        mode: "0755"
        state: directory

    - name: Export nfs directory
      tags: support,nfs
      lineinfile:
        path: /etc/exports
        line: '/data/nfs/ocp *(async,wdelay,rw)'
        create: yes

    - name: Enable nfs
      tags: support,nfs
      service:
        name: nfs-server
        enabled: yes
        state: started

    - name: Open Firewall for nfs
      tags: support,nfs
      firewalld:
       service: nfs
       permanent: yes
       immediate: yes
       state: enabled

# -------------------------------------------------
# ----------------------- setup tftp
    - name: Open Firewall for tftp
      tags: support,tftp
      firewalld:
       service: tftp
       permanent: yes
       immediate: yes
       state: enabled

    - name: Provide tftp config
      tags: support,tftp
      template:
        src: templates/ocp4tftp.j2
        dest:  /etc/xinetd.d/tftp
      register: tftp_cfg

    - name: Enable and start tftp server
      tags: support,tftp
      service:
        name: xinetd
        enabled: yes
        state: restarted
      when: tftp_cfg is changed

# -------------------------------------------------
# ----------------------- prepare PXE boot
# See: https://wiki.centos.org/HowTos/PXE/PXE_Setup
    - name: Copy syslinux files
      tags: support,pxe
      copy:
        src: /usr/share/syslinux/{{item}}
        dest: /var/lib/tftpboot
        remote_src: yes
      with_items:
        - pxelinux.0
        - ldlinux.c32
        - menu.c32
        - memdisk
        - mboot.c32
        - chain.c32

    - name: Create the directories for PXE menus and images
      tags: support,pxe
      file:
        path: /var/lib/tftpboot/{{item}}
        state: directory
      with_items:
        - pxelinux.cfg
        - images
